// Dependencies
import type { Metadata } from "next";

// Providers
import { Providers } from "@/layouts/Providers";

// Styles
import "./globals.css";

export const metadata: Metadata = {
  title: "Image Analytics",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
